CREATE DATABASE :DBNAME;
CREATE USER :PROJECTUSER WITH PASSWORD :PASSWORDDB;
ALTER ROLE :PROJECTUSER SET client_encoding TO 'utf8';
ALTER ROLE :PROJECTUSER SET default_transaction_isolation TO 'read committed';
ALTER ROLE :PROJECTUSER SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE :DBNAME TO :PROJECTUSER;
