# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color_guide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='owner',
            new_name='user',
        ),
    ]
