# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_guide', '0002_auto_20160520_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_name', models.CharField(max_length=100)),
                ('color', models.ManyToManyField(to='color_guide.Color')),
            ],
        ),
    ]
